# when working with external libraries, if the runner doesn't have them by default, we need to install them

name: Generate ASCII Dragon

# whenever i push to this repository, this workflow will be executed. on: -> is the trigger
on: push 

jobs: 
    first_job: # name of the job
        runs-on: ubuntu-latest # where the job should run, ubuntu-latest is Github-hosted runner
        steps: 
        - name: Checkout Code
          uses: actions/checkout@v5

        - name: Install Cowsay
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay CMD
          run: cowsay -f dragon "i am a DRAGON!!!!" >> dragon.txt

        - name: Test if the file exists
          run: grep -i "dragon" dragon.txt

        - name: read file
          run: cat dragon.txt

        - name: list files
          run: ls

